### ISSUE TITLE
wlayers only returning 500 x 500 tiles as Map Requests

### ISSUE THREAD

**Issue by mwhutchi** [nemac/seldon#59]
There was code written a while back due to a limit on a wlayers which no longer seems to be needed. It is creating an issue with the Events wlayers layers' symbology. Derek proposed a change to the code around line 1371: 

options.singleTile = true;
            options.ratio      = 1;
            //possibly remove below logic:
            // if (stringContainsChar(this.url, 'wlayers')) {
                // options.tileSize = new OpenLayers.Size(500,500);
                // options.ratio    = 1;
                // options.buffer   = 2;
            // } else {
                // options.singleTile = true;
                // options.ratio      = 1;
            // }

**Comment by geoderek** [comment]
done
