### ISSUE TITLE
possible loading of layers freezes on specific scenario of panning

### ISSUE THREAD

**Issue by geoderek** [nemac/seldon#62]
Matt W found the following sequence.  Can be reproduced in http://forwarn.forestthreats.org/fcav2/# with the following flow of actions:
1. load up the viewer and zoom in to a dense data area
2. turn off the default layer
3. turn on another layer
4. turn off that layer 
5. turn back on the original layer
6. pan once
7. pan twice and the loading of layers hangs

In trying to recreate this on my own computer I can't.  But, I did verify that this is occurring on Matt's browser.  Could be tricky to troubleshoot, but just wanted to make note of it.

**Comment by violincounter** [comment]
closed with #79
