### ISSUE TITLE
Clicking a legend graphic for a layer with masks enabled deactivates a mask.

### ISSUE THREAD

**Issue by violincounter** [nemac/seldon#77]
Behavior:
- User toggles one or more masks on.
- User activates a layer.
- User clicks the legend graphic for activated layer.
- A mask is disabled and the layer remains active. The legend graphic remains.
- If multiple masks are enabled, clicking the legend graphic disables one mask at a time.

What we want is for all mask layers to be disabled in addition to the parent layer when a legend graphic is clicked.

This issue duplicates #64

**Comment by mwhutchi** [comment]
This *might* be an expected behavior, but not sure. I know it is weird but may be something that was by design. Let's take a look at it together at some point soon.
